### PR TITLE
Changed db-column time

### LINKED ISSUE #21: Wrong duration for user generated trajectory
567312AF-F59F-4489-90FB-A0C4A6EE276A

Yesterday, I freshly installed the app on an iPhone and let it run for a few hours. 51 years is suspiciously close to 1970. I guess there is an issue with computing the duration based on a first / "null" Date object.

### PR DESCRIPTION
**Pull request by schrooom**
Closes issue #21 - see issue for further information.

### CODE REVIEW

File: src/app/shared-services/db/migrations.ts [hunk 1]
```diff
@@ -70,6 +70,10 @@ export const MIGRATIONS = [
     PRIMARY KEY (trajectory, time),
     FOREIGN KEY (trajectory) REFERENCES trajectories(id) ON DELETE CASCADE);`,
 
-  // update date from iso-strings to timestamps
-  `UPDATE points SET time=CAST(strftime('%s', time) AS INT);`,
+  // remove potential duplicate points with very similar timestamp
+  // update date from iso-strings to timestamps and invalidate durationDays for recalculation
+  `DELETE FROM points WHERE time NOT IN (
+    SELECT TIME FROM points GROUP BY strftime('%s', time));
```
Comment (zven) [inline src/app/shared-services/db/migrations.ts:76]: Maybe my SQL got a bit rusty but are you really deleting duplicates here?

To me it reads like you are removing all those points whose timestamps are not part of the set of distinct timestamps. Since this set was created based on all the points (with timestamps) that we are looking at in the outer clause, no point is actually deleted because `time` is included in the set that was created in the inner sql clause.

File: src/app/shared-services/db/migrations.ts [hunk 2]
```diff
@@ -70,6 +70,10 @@ export const MIGRATIONS = [
...
+  UPDATE points SET time=strftime('%s', time);
```
Comment (zven) [inline src/app/shared-services/db/migrations.ts:77]: In case we still have ISO-strings stored in the database, those are reformatted to seconds since 1970, returned as string and then implicitly converted by some sqlite magic into the datetime-format (which is a number)?

If we already have the correct format (a number representing the seconds since 1970) the aforementioned conversion is still carried out but does effectively not change anything?

File: src/app/shared-services/db/migrations.ts (hunk 1 above)
Comment (schrooom) [reply src/app/shared-services/db/migrations.ts:76]: This inner statement `SELECT TIME FROM points GROUP BY strftime('%s', time)` shows all datetimes in current format, but grouped by the new timestamp-representation - therefore elements, where this timestamp would be the same are ignored and only one is shown. Since other elements with the same timestamp are not in there, those are deleted by the outer statement.

Background:
I came across the case, that I had two very similar datetime-strings in my db, somewhat like `2011-08-12T20:17:46.030Z` and  `2011-08-12T20:17:46.050Z` - slightly different times, but both would share the same timestamp in seconds, something like `1313180266`. Since timestamp is one of our primary-keys, this can't happen. Therefore those multiple objects with the exact same timestamp need to be reduced to one. These aren't duplicates now, but are becoming duplicates by reformatting the datetime.

Does this make things clearer?

File: src/app/shared-services/db/migrations.ts (hunk 2 above)
Comment (schrooom) [reply src/app/shared-services/db/migrations.ts:77]: > In case we still have ISO-strings stored in the database, those are reformatted to seconds since 1970, returned as string and then implicitly converted by some sqlite magic into the datetime-format (which is a number)?

Correct. SQLite is quite limited regrading reformatting stuff, therefore I'm relying on the function `strftime()`. I could additionally reformat/cast it back to a number, but SQLite handles this quite well by itself.

> If we already have the correct format (a number representing the seconds since 1970) the aforementioned conversion is still carried out but does effectively not change anything?

If we already have the correct format (number since 1970), then this migration already happened. This migration does only happen once, therefore this should not be possible.

File: src/app/shared-services/db/migrations.ts (hunk 1 above)
Comment (zven) [reply src/app/shared-services/db/migrations.ts:76]: Yes, it does, thanks for the clarification. 👍
